version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cours
      MYSQL_USER: maxence
      MYSQL_PASSWORD: maxence
#    ports:
#      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
